name: kplayer_example
description: Demonstrates how to use the kplayer plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  kplayer:
    path: ../
  audioplayers: ^1.0.0-rc.2
  cupertino_icons: ^1.0.2
  file_picker: ^4.5.1
  universal_io:
  yaml: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^1.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/Introducing_flutter.mp3
